name: frist_pages
description: "A new Mobile project for real Estates In Menofia."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"

  # path: ^1.8.0
#  dependancies
dependencies:
  # a: ^1.0.0
  # path: ^1.8.3
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  sqflite: ^2.3.2
  
  # flutter_native_splash: ^2.3.11
  shared_preferences: ^2.2.3
  bloc: ^8.1.4
  flutter_bloc: ^8.1.5
  pin_code_fields: ^8.0.1
  device_preview: ^1.1.0
  sqflite_common_ffi:
# developer dependancies
dev_dependencies:
  flutter_test:
    sdk: flutter
 
  flutter_native_splash: ^2.3.11
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true

  # assets
  assets:
    - assets/images/
    - assets/images/burger.png
    - assets/images/french-fries.png

    # spash screen
# flutter_native_splash:
#   color: "##E6F5FA"
#   image: "assets/images/logo.jpg"
flutter_native_splash:
  color: "##E6F5FA"
  image: "assets/images/logo.jpg"
  android_12:
    color: "##E6F5FA"
    image: "assets/images/logo.jpg"

flutter_launcher_icons:
  ios: true
  android: true
  image_path_android: "assets/images/logo.jpg"
  image_path_ios: "assets/images/logo.jpg" 
  adaptive_icon_background: "assets/images/logo.jpg" 
  adaptive_icon_foreground: "assets/images/logo.jpg"   
